# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 047cb760327aebbb02222244831ad9853a0821d90007706a30cf0f5c24da0d664841516ace5ed08ef556ef9eb39ae72e96fdb0fd2475c03a63fd80970ee2c499

test:
  secret_key_base: e16864bbf7178beecdf620eeef0dfb648df111eb38dc551adeb33090342afc030d4f7b6f07b352ddd8b5a9bc869adc0deae13f39eb1b6e0530a6c0d0c4b4bad3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
